### ISSUE TITLE
Calculate the scheduled expression from localtime instead of UTC?

### ISSUE THREAD

**Issue by Spiralis** [schyntax/cs-schtick#2]
First of all - I just love this project. It is just about perfect for my needs.

I have found one short-coming though: 
Is there a way to specify the base-date to use when the schedules are created? The users of my app write their own schedules using Schyntax domain language, which I then feed into Schtick. However, if the user writes hours(12), then they expect 12 to be according to the localtime that their computer is running. It seems Schyntax is hardwired to do UTC, unless I am mistaken. Is this something that could be extended here or in Schyntax? I am not suggesting adding anything to the Schyntax domain language for the users to tell whether the input is localtime or UTC. If I could just instantiate Schtick with the needed offset then that would be all I needed. 

If this is a Schyntax change though, this might have to be changed back in CS-Schyntax. Whether it also affects the base Schyntax project I don't know though.

I can help, if someone can help me get a pointer on where and what to change.

**Comment by bretcope** [comment]
I don't love the idea of adding it to Schtick because it makes the schedule definition itself ambiguous as to how it's going to be run. I think that's just asking for confusion. I also don't love the idea of only adding such a feature for C#. It's just one of three official ports, and I'm committed to keeping them as in-sync with each other as possible.

If it's going to be added at all, I think it should be added to Schyntax itself. However, it's a non-trivial change. I've opened [an issue there](https://github.com/schyntax/schyntax/issues/13) for discussion. Feel free to give your input there, especially if you're interested in contributing.

**Comment by Spiralis** [comment]
Thanks :+1:
